#ifndef __CNODECONSTATNTS_H__
#define __CNODECONSTATNTS_H__

class CNodeConstants
{
public:
    enum SubStatusCodes500
    {
        IISNODE_ERROR_ON_EXECUTE_REQ_HANDLER = 1000,
        IISNODE_ERROR_PIPE_CONNECTION = 1001,
        IISNODE_ERROR_PIPE_CONNECTION_BEFORE_PROCESS_TERMINATED = 1002,
        IISNODE_ERROR_CONFIGURE_PIPE_CONNECTION = 1003,
        IISNODE_ERROR_FAILED_INIT_SEND_HTTP_HEADERS = 1004,
        IISNODE_ERROR_FAILED_SERIALIZE_HTTP_HEADERS = 1005,
        IISNODE_ERROR_FAILED_SEND_HTTP_HEADERS = 1006,
        IISNODE_ERROR_FAILED_READ_REQ_BODY = 1007,
        IISNODE_ERROR_FAILED_READ_REQ_BODY_COMPLETED = 1008,
        IISNODE_ERROR_FAILED_INIT_SEND_REQ_BODY = 1009,
        IISNODE_ERROR_FAILED_SEND_REQ_BODY = 1010,
        IISNODE_ERROR_FAILED_INIT_READ_RESPONSE = 1011,
        IISNODE_ERROR_FAILED_ALLOC_MEM_READ_RESPONSE = 1012,
        IISNODE_ERROR_FAILED_PROCESS_HTTP_STATUS_LINE = 1013,
        IISNODE_ERROR_FAILED_PROCESS_HTTP_HEADERS = 1014,
        IISNODE_ERROR_FAILED_PROCESS_RESPONSE_BODY_CHUNK_HEADER = 1015,
        IISNODE_ERROR_FAILED_SEND_RESPONSE_BODY_CHUNK = 1016,
        IISNODE_ERROR_FAILED_FLUSH_RESPONSE_BODY = 1017,
        IISNODE_ERROR_FAILED_FLUSH_RESPONSE_BODY_PARTIAL_FLUSH = 1018
    };

    enum SubStatusCodes503
    {
        IISNODE_ERROR_NOT_ENOUGH_QUOTA = 1000,
        IISNODE_ERROR_FAILED_ACCEPT_REQUEST_APP_RECYCLE = 1001,
        IISNODE_ERROR_INIT_PROCESS_REQUEST = 1002,
        IISNODE_ERROR_PIPE_CONNECTION_TOO_BUSY = 1003
    };
};

#endif