@echo off
echo //
echo // This file was autogenerated in a pre-build step of iisnode by ..\scripts\genDebugRc.bat
echo //
set findStr=%~p0
call set findStr=%%findStr:\src\iisnode\scripts\=\src\iisnode\node-inspector\%%
set /a c=0
setlocal ENABLEDELAYEDEXPANSION
for /F "tokens=*" %%i in ('dir /s /b /a-d %~dp0\..\node-inspector') do call :generateHeaders %%~pnxi %findStr%
echo STRINGTABLE
echo BEGIN
set /a c=0
setlocal ENABLEDELAYEDEXPANSION
for /F "tokens=*" %%i in ('dir /s /b /a-d %~dp0\..\node-inspector') do call :generateStringTable %%~pnxi %findStr%
echo END
set /a c=0
call set findStr=%%findStr:\src\iisnode\scripts\=\src\iisnode\node-inspector\%%
for /F "tokens=*" %%i in ('dir /s /b /a-d %~dp0\..\node-inspector') do call :generateRC %%~pnxi %findStr%
exit /b 0

:generateRC

set /a c=c+1
set line=%1
call set line=%%line:%2=%%
call set file=%%line:\=\\%%
echo F!c! DEBUGGERFILE ^"node-inspector\\%file%^"
GOTO:eof

:generateStringTable

set /a c=c+1
set line=%1
call set line=%%line:%2=%%
call set file=%%line:\=\\%%
echo IDS_!c! ^"%file%^"
GOTO:eof

:generateHeaders

set /a c=c+1
set line=%1
call set line=%%line:%2=%%
call set file=%%line:\=\\%%
echo #define IDS_!c! !c!
GOTO:eof